Catch gateway exceptions in issuer field.
pronamic/wp-pronamic-pay-gravityforms pull request #11
Opened 2022-09-30 13:30 UTC by rvdsteege

Fixes #10.

2022-10-03 09:47 UTC, remcotolsma requested changes
I think this should be catched more upstream:
https://github.com/pronamic/wp-pronamic-pay-gravityforms/blob/d1abd35fca455e382022f0f12363c1f39025169e/src/IssuersField.php#L154

At this point it's not clear why we catch all exceptions on the `$this->get_gateway();` call.

2022-10-04 08:47 UTC, rvdsteege commented
We can catch here:

https://github.com/pronamic/wp-pronamic-pay-gravityforms/blob/d1abd35fca455e382022f0f12363c1f39025169e/src/IssuersField.php#L154

But then we also need 2 additional catches, around the following lines (tested):

- https://github.com/pronamic/wp-pronamic-pay-gravityforms/blob/d1abd35fca455e382022f0f12363c1f39025169e/src/IssuersField.php#L141 (e.g. exceptions via https://github.com/pronamic/wp-pronamic-pay-mollie/blob/c0b2e8a9da16caaeda575225801ff5b3164c0c25/src/Gateway.php#L102-L107 in gateway constructor)
- https://github.com/pronamic/wp-pronamic-pay-gravityforms/blob/d1abd35fca455e382022f0f12363c1f39025169e/src/IssuersField.php#L202

We'll end up with 3 instead of 1 catch. Is that desired?

2022-10-04 11:25 UTC, remcotolsma approved these changes

2022-10-04 11:27 UTC, remcotolsma commented
Discussed https://github.com/pronamic/wp-pronamic-pay-gravityforms/pull/11#issuecomment-1266611876 via Slack.

> But then we also need 2 additional catches, around the following lines (tested):
> 
> - https://github.com/pronamic/wp-pronamic-pay-gravityforms/blob/d1abd35fca455e382022f0f12363c1f39025169e/src/IssuersField.php#L141 (e.g. exceptions via https://github.com/pronamic/wp-pronamic-pay-mollie/blob/c0b2e8a9da16caaeda575225801ff5b3164c0c25/src/Gateway.php#L102-L107 in gateway constructor)
> - https://github.com/pronamic/wp-pronamic-pay-gravityforms/blob/d1abd35fca455e382022f0f12363c1f39025169e/src/IssuersField.php#L202
> 
> We'll end up with 3 instead of 1 catch. Is that desired?

Catch exception around `$options = $issuer_field->get_flat_options();` and `$options = $issuer_field->get_options();` should be sufficient.

@rvdsteege already changed this in https://github.com/pronamic/wp-pronamic-pay-gravityforms/commit/5f46810fe87baeb6a0704c53a13a54120dd4c863, will merge this.

2022-10-04 11:27 UTC, merged